spring:
  datasource:
    url: jdbc:mysql://localhost:33066/task-manager?allowPublicKeyRetrieval=true&useSSL=false
    username: task_manager_db
    password: Qwer!234Asdf
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
